spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URL}
server:
  port: 8024

logging:
  file:
    name: logs/daedalustest.log
    path: daedalustest
  level:
    com.geppetto: info
  pattern:
    dateformat: "dd-MM-yyyy hh:mm:ss aa"



























